<a href="https://colab.research.google.com/github/LeeJaeEun0/Study_230123/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D(%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0%2C_%EC%BC%80%EB%9D%BC%EC%8A%A4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 인공신경망(Artificial Neural Network)
* 인강 두뇌에 대한 계산적 모델을 통해 인공지능을 구현하려는 분야
* 인간의 뇌 구조를 모방: 뉴런과 뉴런 사이에는 전기 신호를 통해 정보를 전달


## 생물학적 신경세포(Biological Neuron Versus)와 인공 신경망(Artificial Neural Network) 비교
* 신경세포(Neuron)

* 인공뉴런(Artificial Neuron)
  * 신경세포 구조를 단순화하여 모델링한 구조 (= 신경세포 구조를 모방한 인공신경망)
  * 노드(Node)와 엣지(Edge)로 표현
  * 하나의 노드 안에서 입력(Input)와 가중치(Weights)를 곱하고 더하는 선형구조(linear)
  * 활성화함수(activation function)를 통한 비선형 구조(non-linear) 표현 가능
  * 선형구조, 비선형 구조를 표현할 수 있음
 
* 인공 신경망(Artificial Neural Network)
  * 여러 개의 인공뉴런들이 모여 연결된 형태
  * 뉴런들이 모인 하나의 단위를 층(layer)이라고 하며, 여러층(multi layer)으로 이루어질 수 있음 => 여러층이 있어야 복잡한 인공지능 구현 가능
  * ex) 입력층(input layer), 은닉층(hidden layer), 출력층(output layer)

## 딥러닝 프레임 워크(DeepLearning Framework)
1. 텐서플로우(Tensorflow)
  * 가장 널리 쓰이는 딥러닝 프레임워크 중에 하나
  * 구글이 주도적으로 개발하는 플랫폼
  * 파이썬, C++ API를 기본적으로 제공하고, 자바스크립트(Java Script), 자바(Java), 고(Go), 스위프트(Swift) 등 다양한 프로그래밍 언엉를 지원
  * tf.keras를 중심으로 고수준 API 통합(2.x 버전)
  * TPU(Tensor Processing Unit) 지원
    * TPU는 GPU보다 전력을 적게 소모, 경제적
    * 일반적으로 32비트(float32)로 수행되는 곱셈 연산을 16비트(float16)로 낮춤
1. 케라스(Keras)
  * 파이싼으로 작성된 고수준 신경망 API로, TensorFlow, CNTK, 혹은 Theano와 함께 사용가능
  * 사용자 친화성, 모듈성, 확장성을 통해 빠르고 간편한 프로토타이핑 가능
  * 컨볼루션 신경망, 순환 신경망, 그리고 둘의 조합까지 모두 지원
  * CPU와 GPU에서 매끄럽게 실행

## 딥러닝 데이터 표현과 연산
  * 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
  * 텐서는 데이터를 담기위한 켄데이터(container)로서 일반적으로 수치형 데이터를 저장

* 보통 6텐서까지 사용하고, 텐서를 더 늘릴 수 있다.


|차원|0D Tensor(Scalar)|1D Tensor(Vector)|2D Tensor(Matrix)|3D Tensor|4D Tensor|5D Tensor|6D Tensor| 
|--|--|--|--|--|--|--|--|
|Rank|0|1|2|3|4|5|6|
|Shape|()|(3,)|(3,3)|(3,3,3)|(3,3,3,3)|(3,3,3,3,3)|(3,3,3,3,3,3)|

### 텐서(Tensor)
* Rank: 축의 개수
* Shape: 형상(각 축에 따른 차원 개수)
* Type: 데이터 타입

In [4]:
import numpy as np
import tensorflow as tf


#### 0D Tensor(scalar)
* 단순히 하나의 숫자를 담고 있는 텐서(tensor)
* 축과 형상이 없음

In [5]:
t0 = tf.constant(1) # constant()를 통해서 텐서로 변환함
print(t0) 
print(tf.rank(t0)) # rank는 차원 단위로 표현 - 0D 

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [8]:
t0 = tf.constant(3)
print(t0) 

tf.Tensor(3, shape=(), dtype=int32)


#### 1D Tensor(Vector)
* 값들을 저장한 리스트와 유사한 텐서
* 하나의 축이 존재

In [12]:
t1= tf.constant([1,2,3]) # constant()를 통해서 텐서로 변환함 - 리스트를 텐서의 형태로 변환
print(t1) # 모양과 3개 있음을 알 수 있음
print(tf.rank(t1)) # 축이 1개

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


#### 2D Tensor(Matrix)
* 행렬과 같은 모양으로 두개의 축이 존재
* 일반적인 수치, 통계 데이터셋이 해당
* 주로 샘플(samples)과 특성(features)을 가진 구조로 사용
  * 샘플 - 행, 특성 - 열

In [13]:
t2 = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(t2)
print(tf.rank(t2)) # 축이 2개

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


#### 3D Tensor
* 큐브(cube)와 같은 모양으로 세개의 축이 존재
* 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당
* 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등의 존재
* 주로 샘플(samples), 타임스텝(timesteps), 특성(features)을 가진 구조로 사용
  * 타임스텝에 따라서 샘플과 특성이 존재하는 구조
    * 1반 - 타임스텝
    * 샘플(행) - 학생 개체 정보
    * 특성(열) - 시험 점수 등

In [15]:
t3 = tf.constant([[[1,2,3],[4,5,6],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]],
                  [[1,2,3],[4,5,6],[7,8,9]]])
print(t3)
print(tf.rank(t3))

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


#### 4D Tensor
* 4개의 축
* 컬러 이미지가 대표적인 사례 (흑백 이미지 데이터는 3D Tensor로 가능)
* 주로 샘플(samples), 높이(height), 너비(width), 컬러채널(channel)을 가진 구조로 사용
  * 샘플 - 여러 이미지들이 있음
  * 이미지 한 장의 너비와 높이, 채널(뎁스라고도 하며 이미지의 색상 정보를 가짐)

#### 5D Tensor
* 5개의 축
* 비디오 데이터가 대표적인 사례
* 주로 샘플(samples), 프레임(frames), 높이(height), 너비(width), 컬러채널(channel)을 가진 구조로 사용

### 텐서 데이터 타입
* 텐서의 기본 dtype
  * 정수형 텐서: int32
  * 실수형 텐서: float32
  * 문자형 텐서: string

* int32, float32, string 타입 외에도 float64, int8 타입 등이 존재
* 연산시 텐서의 타입 일치 필요
* 타입변환에는 ft.cast() 사용


In [16]:
i =tf.constant(2) # dtype=int32
print(i)

tf.Tensor(2, shape=(), dtype=int32)


In [17]:
f =tf.constant(2.) # dtype=float32
print(f)

tf.Tensor(2.0, shape=(), dtype=float32)


In [18]:
s =tf.constant('Jaeeun') # dtype=string
print(s)

tf.Tensor(b'Jaeeun', shape=(), dtype=string)


In [21]:
f16 = tf.constant(2., dtype=tf.float16)
print(f16)

tf.Tensor(2.0, shape=(), dtype=float16)


In [22]:
i8 = tf.constant(2, dtype=tf.int8)
print(i8)

tf.Tensor(2, shape=(), dtype=int8)


In [23]:
f32 = tf.cast(f16, tf.float32) # float16 -> float32로 변환
print(f32)

tf.Tensor(2.0, shape=(), dtype=float32)


In [24]:
i32 = tf.cast(i8, tf.int32) #  int8 -> int32로 변환
print(i32)

tf.Tensor(2, shape=(), dtype=int32)


### 텐서 연산

In [26]:
# 텐서간 더하기 연산
print(tf.constant(2) + tf.constant(2))
print(tf.add(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [27]:
# 텐서간 빼기 연산
print(tf.constant(2) - tf.constant(2))
print(tf.subtract(tf.constant(2), tf.constant(2)))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [28]:
# 텐서간 곱하기 연산
print(tf.constant(2) * tf.constant(2))
print(tf.multiply(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [29]:
# 텐서간 나누기 연산
print(tf.constant(2) / tf.constant(2))
print(tf.divide(tf.constant(2), tf.constant(2)))

tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)


In [30]:
# 텐서가 나누기 - 정수 나누기 실수
# 같은 형이 아닌 경우 연산할 수 없음
print(tf.constant(2) / tf.constant(2.2))

TypeError: ignored

In [31]:
# 텐서간 형(dtype)을 맞춰서 연산함 - cast이용
print(tf.cast(tf.constant(2), tf.float32) + tf.constant(2.2))

tf.Tensor(0.9090909, shape=(), dtype=float32)


## 딥러닝 구조 및 학습
* 딥러닝 구조와 학습에 필요한 요소
  * **모델(네트워크)**를 구성하는 **레이어(layer)**
  * **입력 데이터**와 그에 따른 **목적(결과)[=학습결과]**
  * 학습시에 사용할 피드백을 정의하는 **손실함수(loss function)** 
    - 학습 정도(잘 진행됐는지, 안됐는지)를 확인 할 수 있는 손실함수
  * 학습 진행 방식을 결정하는 옵티마이저(optimizer)
    - 최적화와 관련

### 레이어(Layer)
* 신경망의 핵심 데이터를 구조
* 하나 이상의 텐서를 입력받아 하나 이상의 텐서를 출력하는 데이터 처리 모듈
  * 대부분 m:m의 관계
* 상태가 없는 레이어도 있지만, 대부분 **가중치(weight)**라는 레이어 상태를 가짐
* 가중치는 확률적 경사 하강법에 의해 학습되는 하나 이상의 텐서

* Keras에서 사용되는 주요 레이어
  * Dense
  * Activation
  * Flatten
  * Input

In [32]:
from tensorflow.keras.layers import Dense, Activation, Flatten, Input

#### Dense
* **완전연결계충(Fully-Connected Layer)**
  * 모든 노드가 연결된 상태
* 노드수(유닛수), 활성화 함수(activation)등을 지정
* `name`을 통한 레이어간 구분 가능
  * 이름을 지정가능 - 호출도 가능
* 가중치 초기화(`kernel_initializer`) - 노드의 가중치를 미리 지정가능
  * 신경망의 성능에 큰 영향을 주는 요소
  * 보통 가중치의 초기값으로 0에 가까운 무작위 값 사용
  * 특정 구조의 신경망을 동일한 학습데이터로 학습시키더라도, 가중치의 초기값에 따라 학습된 신경망의 성능 차이가 날 수 있음
  * 오차역전파 알고리즘은 기본적으로 경사하강법을 사용하기때문에 최적화가 아닌 지역해에 빠질 가능성이 있음
  * Keras에서는 기본적으로 Glorot uniform 가중치(Xavier 분포 초기화), zero bias로 초기화
  * `kernel_initializer` 인자를 통해 다른 가중치 초기화 지정가능
  * Keras에서 제공;하는 가중치 초기화 종류: https://keras.io/api/layers/initializers/

In [33]:
Dense(10, activation='softmax') # 노드(유닛수) :10 , 활성화 함수는 softmax

In [34]:
Dense(10, activation='relu', name='Dense Layer') # 노드(유닛수) :10 , 활성화 함수는 relu, 이름은 Dense Layer

In [37]:
Dense(10, kernel_initializer='he_normal', name='Dense Layer') # 노드(유닛수) :10, 가중치 초기화 방법: he_normal, 이름은 Dense Layer

#### Activation
* Dense layer에서 미리 활성화 함수를 지정할 수도 있지만 필요에 따라 별도 레이어를 만들어 줄 수 있음
* Keras에서 제공하는 활성화 함수(activation funcion) 종류: https://keras.io/ko/activations/

*  종류
  * Sigmoid
    * 대표적인 함수
  * tanh
  * ReLU
    * 0이후 부터 값이 올라감
  * Leaky ReLU
    * 음수를 표현할 수 있음
  * Maxout
  * ELU

In [39]:
# Dense에서 선언
dense = Dense(10, activation='relu', name='Dense Layer')
# 별도의 레이어에서 선언 가능
Activation(dense)

#### Flatten
* 배치 크기(또는 데이터 크기)를 제외하고 데이터를 1차원으로 쭉 펼치는 작업
* 예시
```
(128, 3, 2, 2) -> (128,12)
```



In [40]:
Flatten(input_shape=(128,3,3,3))

#### Input
* 모델의 입력을 정의
* `shape`, `dtype`을 포함
* 하나의 모델은 여러 개의 입력을 가질 수 있음
* `summary`메소드를 통해서 보이지 않음

In [45]:
Input(shape=(28,28), dtype=tf.float32) # input_1

<KerasTensor: shape=(None, 28, 28) dtype=float32 (created by layer 'input_1')>

In [46]:
Input(shape=(8,), dtype=tf.int32) # input_2

<KerasTensor: shape=(None, 8) dtype=int32 (created by layer 'input_2')>

### 모델(Model)
* 딥러닝 모델은 레이어로 만들어진 비순환 유향 그래프(Directed Acyclic Grap)
  * 순환 즉 사이클이 없는 그래프

#### 모델 구성
  * `sequential()`
  * 서브클래싱(subclassing)
  *  함수형 API

##### Sequential()
* 모델이 순차적인 구조로 진행할 때 사용
* 간단한 방법
  * Sequential 객체 생성 후, add()를 이용한 방법
  * Sequential 인자에 한번에 추가하는 방법
* 다중 입력 및 출력이 존재하는 등의 복잡한 모델을 구성할 수 없음